/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 15:38:16 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.nio.BufferOverflowException;
import java.nio.CharBuffer;
import java.util.ArrayDeque;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Stack;
import java.util.TreeSet;
import java.util.UnknownFormatConversionException;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.FilterHelpAppendable;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelpAppendable_ESTest extends HelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("Dh", linkedList0, vector0, treeSet0);
      textHelpAppendable0.appendTable(tableDefinition0);
      assertEquals(74, TextHelpAppendable.DEFAULT_WIDTH);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      textHelpAppendable0.appendParagraph(stringBuffer0);
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      StringWriter stringWriter0 = new StringWriter(74);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      textHelpAppendable0.appendHeader((-1268), stringBuffer0);
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[4];
      textHelpAppendable0.appendFormat("+nn.V", objectArray0);
      assertEquals(1, textHelpAppendable0.getLeftPad());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("w/=}B_%3v>e;z]");
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintStream0);
      textHelpAppendable0.appendTitle("w/=}B_%3v>e;z]");
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Vector<CharSequence> vector0 = new Vector<CharSequence>();
      textHelpAppendable0.appendList(false, vector0);
      assertEquals(74, TextHelpAppendable.DEFAULT_WIDTH);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Stack<List<String>> stack1 = new Stack<List<String>>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(stack1);
      TableDefinition tableDefinition0 = TableDefinition.from("", stack0, (List<String>) null, arrayDeque0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      HashSet<Option> hashSet0 = new HashSet<Option>(7);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) hashSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      linkedList0.addAll((Collection<? extends TextStyle>) list0);
      LinkedList<String> linkedList1 = new LinkedList<String>();
      TableDefinition tableDefinition1 = TableDefinition.from("org.apache.commons.io.file.Counters$BigIntegerCounter", linkedList0, linkedList1, (Iterable<List<String>>) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[7];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("A36} -q#y%q @w]@ ", objectArray0);
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = 'q'
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(40);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append((CharSequence) charBuffer0);
      Object[] objectArray0 = new Object[8];
      // Undeclared exception!
      try { 
        filterHelpAppendable0.appendParagraphFormat("|\"`=^?Hm", objectArray0);
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[9];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad((-785));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("%Spf^-4qB:", (Object[]) null);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(3);
      textHelpAppendable0.setIndent((-1543));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraph(charBuffer0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter(3470);
      StringWriter stringWriter1 = stringWriter0.append('j');
      StringBuffer stringBuffer0 = stringWriter1.getBuffer();
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader(0, stringBuffer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[7];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendFormat((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(40);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      Object[] objectArray0 = new Object[8];
      textHelpAppendable0.appendParagraphFormat("|\"`=^?Hm", objectArray0);
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }
}
