/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 15:39:59 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("SFjIZgAYk,=I`7f", linkedList0, stack0, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = (Iterable<List<String>>)tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TableDefinition tableDefinition0 = TableDefinition.from("org.apache.commons.cli.help.TableDefinition$1", (List<TextStyle>) null, (List<String>) null, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("SFjIZgAYk,=I`7f", linkedList0, stack0, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertFalse(list0.contains("SFjIZgAYk,=I`7f"));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("org.apache.commons.cli.help.TableDefinition$1", arrayList0, stack0, (Iterable<List<String>>) null);
      stack0.add("org.apache.commons.cli.help.TableDefinition$1");
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.contains("org.apache.commons.cli.help.TableDefinition$1"));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>();
      ArrayList<List<String>> arrayList1 = new ArrayList<List<String>>(priorityQueue0);
      TableDefinition tableDefinition0 = TableDefinition.from("", (List<TextStyle>) null, arrayList0, arrayList1);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Vector<List<String>> vector0 = new Vector<List<String>>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>(vector0);
      TableDefinition tableDefinition0 = TableDefinition.from("", stack0, linkedList0, treeSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      Vector<List<String>> vector1 = new Vector<List<String>>(1729);
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, vector0, (List<String>) null, vector1);
      String string0 = tableDefinition0.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("SFjIZgAYk,=I`7f", linkedList0, stack0, (Iterable<List<String>>) null);
      String string0 = tableDefinition0.caption();
      assertEquals("SFjIZgAYk,=I`7f", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayDeque0);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNotNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayDeque0);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayDeque0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertFalse(list0.isEmpty());
  }
}
