/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 15:25:00 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.cli.help.Util;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Util_ESTest extends Util_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Util.rtrim("a");
      Util.isWhitespace('B');
      // Undeclared exception!
      try { 
        Util.repeatSpace((-1491));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      char[] charArray0 = new char[1];
      charArray0[0] = '7';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      charBuffer0.flip();
      Util.defaultValue(charBuffer0, charBuffer0);
      char char0 = 'u';
      // Undeclared exception!
      try { 
        Util.repeat((-1), 'u');
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Util.defaultValue("", "");
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = Util.repeat(1730, '4');
      Util.indexOfNonWhitespace(string0, 442);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Util.ltrim("4>;@|G*a&-\u001Fh<y4#");
      Util.indexOfNonWhitespace("4>;@|G*a&-\u001Fh<y4#", 230);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Util.defaultValue((CharSequence) null, (CharSequence) null);
      Util.indexOfNonWhitespace((CharSequence) null, 1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Util.repeatSpace(0);
      Util.indexOfNonWhitespace("", 0);
      String string0 = Util.repeatSpace(1918);
      Util.isEmpty("");
      Util.ltrim(string0);
      Util.repeatSpace(384);
      Util.repeat(1918, '{');
      Util.rtrim("");
      Util.rtrim(string0);
      // Undeclared exception!
      try { 
        Util.indexOfNonWhitespace("                                                                                                                                                                                                                                                                                                                                                                                                ", (-228));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = Util.repeatSpace(2089);
      Util.rtrim(string0);
      Util.rtrim((String) null);
      Util.isWhitespace('?');
      Util.repeatSpace(2089);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Util.repeat(0, '!');
      Util.indexOfNonWhitespace("", (-1097));
      Util.isEmpty("");
      Util.isWhitespace('H');
      Util.indexOfNonWhitespace("", 0);
      Util.isWhitespace('H');
      Util.isWhitespace(' ');
      Util.isEmpty("");
      Util.indexOfNonWhitespace("", (-3996));
      Util.rtrim("");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = Util.repeat(2531, '*');
      Util.isEmpty(string0);
      Util.ltrim("");
      Util.isEmpty("");
      Util.indexOfNonWhitespace(string0, 0);
      Util.rtrim("");
      Util.repeatSpace(0);
      Util.repeat(0, '*');
      Util.isWhitespace('*');
      CharBuffer charBuffer0 = CharBuffer.allocate(2531);
      CharBuffer charBuffer1 = charBuffer0.put(0, ')');
      Util.defaultValue(charBuffer0, charBuffer0);
      Util.indexOfNonWhitespace("", 0);
      Util.repeat(1, ')');
      Util.isWhitespace('}');
      Util.indexOfNonWhitespace(charBuffer1, 2531);
      Util.isEmpty(string0);
      // Undeclared exception!
      try { 
        Util.indexOfNonWhitespace(charBuffer0, (-522));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Util.rtrim("");
      Util.ltrim("");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Util.ltrim("");
      Util.repeat(0, 'R');
      Util.isWhitespace('&');
      Util.ltrim("");
      Util.indexOfNonWhitespace("", 0);
      Util.ltrim("");
      Util.isWhitespace('_');
      Util.indexOfNonWhitespace("", (-1));
      Util.defaultValue("A) 7HfU//@4&g \"$1", "");
      Util.repeat(894, '_');
      Util.isWhitespace('R');
      Util.isWhitespace('3');
      Util.rtrim(")f4(lcAtX9A_ucP5QM");
      Util.rtrim(")f4(lcAtX9A_ucP5QM");
      Util.indexOfNonWhitespace(")f4(lcAtX9A_ucP5QM", 1);
      Util.repeat(1785, 'e');
      Util.isEmpty(")f4(lcAtX9A_ucP5QM");
      Util.repeatSpace(835);
      Util.isEmpty("______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
      Util.ltrim((String) null);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Util.rtrim("org.apache.commons.cli.help.Util");
      Util.isEmpty("org.apache.commons.cli.help.Util");
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(1420);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 363, 363);
      CharBuffer charBuffer2 = charBuffer0.put(charBuffer1);
      charBuffer0.mark();
      Util.isEmpty(charBuffer0);
      Util.indexOfNonWhitespace(charBuffer2, 0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Util.rtrim("@3I0<tnx)@}");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Util.isWhitespace('X');
      Util.rtrim("");
      Util.isWhitespace('\u000F');
      Util.repeat('\u000F', 'X');
      Util.rtrim("");
      Util.isEmpty("");
      Util.isWhitespace('\u000F');
      Util.rtrim("u]$");
      Util.ltrim("");
      Util.isWhitespace('X');
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Util.isWhitespace('N');
      String string0 = Util.rtrim("");
      Util.isWhitespace('3');
      String string1 = Util.repeatSpace(4458);
      Util.isWhitespace('}');
      Util.isEmpty("");
      int int0 = Util.indexOfNonWhitespace("8%$JfLSW.xV,[UJV", 4458);
      assertEquals((-1), int0);
      
      String string2 = Util.rtrim(string1);
      assertTrue(string2.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String string0 = Util.defaultValue("", " 5Z]*l|oj^B\"@-Y");
      String string1 = Util.defaultValue(" 5Z]*l|oj^B\"@-Y", "#4Lvk");
      assertTrue(string1.equals((Object)string0));
      
      String string2 = Util.repeatSpace(4);
      assertEquals("    ", string2);
      
      String string3 = Util.ltrim(" 5Z]*l|oj^B\"@-Y");
      assertEquals("5Z]*l|oj^B\"@-Y", string3);
  }
}
