/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 15:19:10 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.sql.DataTruncation;
import java.time.format.FormatStyle;
import java.time.format.ResolverStyle;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Properties;
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.text.TextStringBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommandLine_ESTest extends CommandLine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption('-');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.setDeprecatedHandler((Consumer<Option>) null);
      CommandLine commandLine0 = commandLine_Builder1.get();
      assertNotNull(commandLine0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option((String) null, "true", true, "true");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      commandLine_Builder0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption(")k");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option[] optionArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Option[]) null);
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = new String[4];
      String[] stringArray1 = commandLine0.getParsedOptionValues(optionGroup0, stringArray0);
      assertEquals(4, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer[] integerArray0 = new Integer[0];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues(optionGroup0, (Supplier<Integer[]>) supplier0);
      assertEquals(0, integerArray1.length);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues((Option) null, (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Option option0 = new Option("i", "java.vWinfo");
      CommandLine commandLine0 = new CommandLine();
      ResolverStyle[] resolverStyleArray0 = new ResolverStyle[1];
      ResolverStyle[] resolverStyleArray1 = commandLine0.getParsedOptionValues(option0, resolverStyleArray0);
      assertSame(resolverStyleArray0, resolverStyleArray1);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      Option[] optionArray0 = new Option[0];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues(option0, (Supplier<Option[]>) supplier0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      String[] stringArray0 = commandLine0.getParsedOptionValues(option0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues((String) null, (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getArgs();
      Object[] objectArray0 = commandLine0.getParsedOptionValues("2yEXi", (Object[]) stringArray0);
      assertSame(stringArray0, objectArray0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[6];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues((String) null, (Supplier<Object[]>) supplier0);
      assertSame(objectArray1, objectArray0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Option>[] linkedListArray0 = (LinkedList[]) Array.newInstance(LinkedList.class, 0);
      Supplier<LinkedList<Option>[]> supplier0 = (Supplier<LinkedList<Option>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(linkedListArray0).when(supplier0).get();
      LinkedList<Option>[] linkedListArray1 = commandLine0.getParsedOptionValues("i", supplier0);
      assertSame(linkedListArray0, linkedListArray1);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Object[] objectArray0 = commandLine0.getParsedOptionValues(")k");
      assertEquals(1, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getParsedOptionValues('x', (String[]) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList[] linkedListArray0 = (LinkedList[]) Array.newInstance(LinkedList.class, 0);
      LinkedList<Class<Option>>[] linkedListArray1 = commandLine0.getParsedOptionValues('Q', (LinkedList<Class<Option>>[]) linkedListArray0);
      assertSame(linkedListArray0, linkedListArray1);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[5];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues('o', (Supplier<Object[]>) supplier0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[0];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues('o', (Supplier<Object[]>) supplier0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("o", false, (String) null);
      OptionGroup optionGroup0 = new OptionGroup();
      Option option1 = (Option)commandLine0.getParsedOptionValue(optionGroup0, (Object) option0);
      assertEquals((-1), option1.getArgs());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = commandLine0.getParsedOptionValue((Option) null, (Option) null);
      assertNull(option0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Object object0 = commandLine0.getParsedOptionValue(option0);
      assertEquals(")k", object0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.option("h");
      Option option0 = commandLine0.getParsedOptionValue("Y0`E[mWeQ^q`X1", (Supplier<Option>) option_Builder1);
      assertEquals(104, option0.getId());
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getParsedOptionValue("", (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      String string0 = commandLine0.getParsedOptionValue(")k");
      assertEquals(")k", string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getParsedOptionValue('i', (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[0];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getParsedOptionValue('F', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getParsedOptionValue(':', (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("i", "java.vWinfo");
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine_Builder0.addOption(option0);
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(1, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      String[] stringArray0 = commandLine0.getOptionValues("THROW");
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      char[] charArray0 = new char[9];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0, 0);
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("STOP", true, "LETTERS");
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, false, (String) null);
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("o", false, (String) null);
      String string0 = commandLine0.getOptionValue(option0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, true, "^`");
      String string0 = commandLine0.getOptionValue(option0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      String string0 = commandLine0.getOptionValue(option0);
      assertEquals(")k", string0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", "", true, "options");
      option0.processValue("");
      commandLine_Builder0.addOption(option0);
      String string0 = commandLine0.getOptionValue(option0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[3];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getOptionValue("sJe501?0pGO", (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((String) null);
      String string0 = commandLine0.getOptionValue((String) null, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("8Xcb(I$G,tk", "tR>\"[M9Yfj>nDqZ`jf");
      assertEquals("tR>\"[M9Yfj>nDqZ`jf", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      String string0 = commandLine0.getOptionValue(")k");
      assertEquals(")k", string0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('V', (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder(" \"*96 D8;~*R|>X(W");
      String string0 = commandLine0.getOptionValue('y', (Supplier<String>) textStringBuilder0);
      assertEquals(" \"*96 D8;~*R|>X(W", string0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('P', (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('.', "Exception found converting ");
      assertEquals("Exception found converting ", string0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Properties properties0 = commandLine0.getOptionProperties(")k");
      assertFalse(properties0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Object object0 = commandLine0.getOptionObject(")k");
      assertEquals(")k", object0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("j_", true, "j_");
      commandLine_Builder0.addOption(option0);
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, false, (String) null);
      option0.setLongOpt("");
      commandLine0.addOption(option0);
      int int0 = commandLine0.getOptionCount("");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg("org.apache.commons.io.file.Counters$NoopCounter");
      String[] stringArray0 = commandLine0.getArgs();
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg("org.apache.commons.io.file.Counters$NoopCounter");
      List<String> list0 = commandLine0.getArgList();
      assertTrue(list0.contains("org.apache.commons.io.file.Counters$NoopCounter"));
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Class<ResolverStyle> class0 = ResolverStyle.class;
      option0.setType(class0);
      try { 
        commandLine0.getParsedOptionValues(option0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.ClassNotFoundException: Class ')k.class' should be in target project, but could not be found!
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Class<FormatStyle> class0 = FormatStyle.class;
      option0.setType(class0);
      try { 
        commandLine0.getParsedOptionValues(")k");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.ClassCastException: Cannot cast java.lang.String to java.time.format.FormatStyle
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("args", "", false, "");
      Option.Builder option_Builder0 = Option.builder((String) null);
      try { 
        commandLine0.getParsedOptionValue(option0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Class<Object> class0 = Object.class;
      option0.setType(class0);
      try { 
        commandLine0.getParsedOptionValue(option0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.ClassNotFoundException: Class ')k.class' should be in target project, but could not be found!
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      commandLine_Builder0.addOption(option0);
      // Undeclared exception!
      try { 
        commandLine0.getOptionProperties((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((Option) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Object[] objectArray0 = new Object[4];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getParsedOptionValues((OptionGroup) null, (Supplier<String[]>) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Class<Object>[] classArray0 = commandLine0.getParsedOptionValues((Option) null, (Supplier<Class<Object>[]>) null);
      assertNull(classArray0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue(optionGroup0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, ">}{<|", false, "R/ia");
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue(option0, supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue((Option) null, (Supplier<Object>) supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues((Option) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("options", "options");
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      char[] charArray0 = new char[4];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("j_", true, "j_");
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) "j_");
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("j_", string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, true, "E|tECusyVHxR+9.:");
      String[] stringArray0 = new String[0];
      String[] stringArray1 = commandLine0.getParsedOptionValues(option0, stringArray0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      int int0 = commandLine0.getOptionCount("!+C7vavTCf_g,:c`om4");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("o", false, (String) null);
      Object[] objectArray0 = commandLine0.getParsedOptionValues(option0);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      String[] stringArray0 = commandLine0.getParsedOptionValues("_s1EJgF3)B8-@4,Wf", (Supplier<String[]>) supplier0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList[] linkedListArray0 = (LinkedList[]) Array.newInstance(LinkedList.class, 3);
      LinkedList<Class<Integer>>[] linkedListArray1 = commandLine0.getParsedOptionValues("E|tECusyVHxR+9.:", (LinkedList<Class<Integer>>[]) linkedListArray0);
      assertSame(linkedListArray1, linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Integer> supplier0 = (Supplier<Integer>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer integer0 = commandLine0.getParsedOptionValue("AWhz&}vcq", (Supplier<Integer>) supplier0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("printWriter");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues("r3");
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues("N@mYiT,r");
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("(w)+", (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption("VQAyrc}h");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Option option0 = new Option("i", "java.vWinfo");
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue(option0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, true, "E|tECusyVHxR+9.:");
      Option option1 = commandLine0.getParsedOptionValue(option0, option0);
      assertEquals("E|tECusyVHxR+9.:", option1.getDescription());
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer integer0 = commandLine0.getParsedOptionValue("");
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Properties properties0 = commandLine0.getOptionProperties(option0);
      assertFalse(properties0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      commandLine_Builder0.addOption(option0);
      Properties properties0 = commandLine0.getOptionProperties(option0);
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("printWriter", "printWriter");
      optionGroup0.setSelected(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption((OptionGroup) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.deprecated();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("j_", true, "j_");
      commandLine_Builder0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.deprecated();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      String string0 = commandLine0.getOptionValue("", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("f", "f");
      optionGroup0.setSelected(option0);
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Supplier<Object[]>) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      FormatStyle[] formatStyleArray0 = commandLine0.getParsedOptionValues((OptionGroup) null);
      assertNull(formatStyleArray0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      String[] stringArray0 = commandLine0.getParsedOptionValues(option0, (Supplier<String[]>) supplier0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) null);
      String string0 = commandLine0.getParsedOptionValue((OptionGroup) null, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, false, (String) null);
      Object object0 = commandLine0.getParsedOptionValue(option0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues((OptionGroup) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      String string0 = commandLine0.getOptionValue(optionGroup0, "options");
      assertEquals(")k", string0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) null);
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals(")k", string0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("THROW", ")k", true, "options");
      option0.processValue(")k");
      commandLine_Builder0.addOption(option0);
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      Object object0 = commandLine0.getParsedOptionValue(option0, (Supplier<Object>) supplier0);
      assertEquals(")k", object0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addOption((Option) null);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.addArg((String) null);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption((Option) null);
      assertSame(commandLine_Builder1, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg("j_");
      assertSame(commandLine_Builder1, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg((String) null);
      assertSame(commandLine_Builder1, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer integer0 = commandLine0.getParsedOptionValue(optionGroup0, (Integer) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Object object0 = commandLine0.getParsedOptionValue(optionGroup0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue('~', (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues('o');
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((String) null, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(0, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      List<String> list0 = commandLine0.getArgList();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      Option option0 = new Option("R", "R");
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue(option0, "R");
      assertEquals("R", string0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getOptionObject('R');
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      DataTruncation[] dataTruncationArray0 = new DataTruncation[0];
      DataTruncation[] dataTruncationArray1 = commandLine0.getParsedOptionValues(optionGroup0, dataTruncationArray0);
      assertSame(dataTruncationArray1, dataTruncationArray0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Properties properties0 = commandLine0.getOptionProperties((String) null);
      assertTrue(properties0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getOptionObject("h");
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Class<Integer>[] classArray0 = commandLine0.getParsedOptionValues('Q');
      assertNull(classArray0);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      int int0 = commandLine0.getOptionCount('');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) null);
      String string0 = commandLine0.getOptionValue('R', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Integer integer0 = new Integer(0);
      Integer integer1 = commandLine0.getParsedOptionValue('w', integer0);
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('F', "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Iterator<Option> iterator0 = commandLine0.iterator();
      assertNotNull(iterator0);
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("printWriter", "printWriter");
      optionGroup0.setSelected(option0);
      Supplier<ResolverStyle> supplier0 = (Supplier<ResolverStyle>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      commandLine0.getParsedOptionValue(optionGroup0, (Supplier<ResolverStyle>) supplier0);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues('Q', (Supplier<Integer[]>) supplier0);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("j_", true, "j_");
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getParsedOptionValue("", "org.apache.commons.io.file.Counters$NoopCounter");
      assertEquals("org.apache.commons.io.file.Counters$NoopCounter", string0);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getParsedOptionValue('G');
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[1];
      Object[] objectArray1 = commandLine0.getParsedOptionValues('F', objectArray0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('Y');
      assertNull(string0);
  }
}
