/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 15:15:14 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      option0.setArgs((-15));
      boolean boolean0 = option0.requiresArg();
      assertFalse(option0.hasArg());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.valueSeparator(' ');
      option_Builder0.numberOfArgs(6);
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      option0.processValue(" since ");
      assertEquals("", option0.getValue());
      assertEquals(6, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.hasArgs();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Option option0 = new Option("9", "9", false, "9");
      option0.isValuesEmpty();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Option option0 = new Option((String) null, true, "}LSE_O rydUOSH#(");
      option0.processValue("}LSE_O rydUOSH#(");
      boolean boolean0 = option0.isValuesEmpty();
      assertFalse(option0.hasLongOpt());
      assertFalse(boolean0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Option option0 = new Option("9", false, "9");
      option0.setRequired(true);
      boolean boolean0 = option0.isRequired();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.optionalArg(true);
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasOptionalArg();
      assertTrue(boolean0);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      option0.processValue("");
      option0.getValuesList();
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.valueSeparator('2');
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      char char0 = option0.getValueSeparator();
      assertEquals((-1), option0.getArgs());
      assertEquals('2', char0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.valueSeparator('K');
      option_Builder0.longOpt("$H<}h");
      Option option0 = option_Builder0.get();
      char char0 = option0.getValueSeparator();
      assertEquals('K', char0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      option0.getValue((String) null);
      assertEquals("", option0.getLongOpt());
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      String string0 = option0.getValue("");
      assertEquals((-1), option0.getArgs());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.optionalArg(true);
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      option0.processValue(" since ");
      String string0 = option0.getValue(0);
      assertTrue(option0.hasOptionalArg());
      assertNotNull(string0);
      assertEquals(1, option0.getArgs());
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.valueSeparator(' ');
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      option_Builder1.numberOfArgs(0);
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      assertTrue(option0.hasOptionalArg());
      
      option0.processValue(" since ");
      String string0 = option0.getValue(0);
      assertEquals("", string0);
      assertEquals(0, option0.getArgs());
      assertFalse(option0.hasArg());
      assertNotNull(string0);
      assertFalse(option0.hasArgs());
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.setArgs(2672);
      option0.processValue("n!d|EO)TLdEZ`'04Ev?");
      option0.getValue();
      assertEquals(2672, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("value");
      option_Builder0.since("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.since("");
      option_Builder0.longOpt(");+Is71E`\\#: B@ :e");
      Option option0 = option_Builder1.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("\"");
      Option option0 = option_Builder0.get();
      option0.setLongOpt((String) null);
      option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALlOWE", "&6vvTg5R9%", true, "&6vvTg5R9%");
      String string0 = option0.getLongOpt();
      assertEquals("&6vvTg5R9%", string0);
      assertEquals("&6vvTg5R9%", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      String string0 = option0.getKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      String string0 = option0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Option option0 = new Option("$0f", "$0f");
      option0.setDescription("");
      option0.getDescription();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.deprecated();
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("value");
      option_Builder0.numberOfArgs(0);
      Option option0 = option_Builder0.get();
      int int0 = option0.getArgs();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Option option0 = new Option((String) null, "8;Pi`|mx&~I");
      int int0 = option0.getArgs();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Option option0 = new Option("Z8DkJ", "Z8DkJ", true, "w7 F ");
      option0.setArgName("w7 F ");
      option0.getArgName();
      assertEquals("w7 F ", option0.getDescription());
      assertEquals("Z8DkJ", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Option option0 = new Option("V", true, "");
      option0.setArgName("");
      option0.getArgName();
      assertEquals("", option0.getDescription());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Option option0 = new Option("V", true, "");
      option0.acceptsArg();
      assertFalse(option0.hasLongOpt());
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, false, "8D_<M$NEaw~ynkI&~");
      boolean boolean0 = option0.acceptsArg();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        option0.setType(object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.setArgs(2479);
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.setArgs(2479);
      option0.processValue("n!d|EO)TLdEZ`'04Ev?");
      try { 
        option0.getValue(2479);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 2479, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Option option0 = new Option((String) null, true, "}LSE_O ryddUOSH#(");
      option0.setLongOpt("");
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, "*QO_KQ");
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      // Undeclared exception!
      try { 
        Option.builder("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("!bpl/lr#vMYqr", true, "!bpl/lr#vMYqr");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name '!'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("", "k-hef1E.B-A", true, ": ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("org.apache.commons.cli.Option$Builder", "org.apache.commons.cli.Option$Builder");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'org.apache.commons.cli.Option$Builder' contains an illegal character : '.'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Option option0 = new Option("$0f", "$0f");
      option0.isDeprecated();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.deprecated();
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.isDeprecated();
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Option option0 = new Option("Deprecated", "", false, "");
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals((-1), option0.getArgs());
      assertEquals("", option0.getLongOpt());
      assertFalse(boolean0);
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Option option0 = new Option("V", true, "");
      boolean boolean0 = option0.hasArgs();
      assertFalse(option0.hasLongOpt());
      assertEquals("", option0.getDescription());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.setArgs(2672);
      boolean boolean0 = option0.hasArgs();
      assertEquals(2672, option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      assertFalse(option0.hasArgs());
      
      option0.setArgs((-2));
      boolean boolean0 = option0.hasArgs();
      assertEquals((-2), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      boolean boolean0 = option0.hasArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Option option0 = new Option("Z8DkJ", "Z8DkJ", true, "w7 F ");
      option0.processValue("");
      String string0 = option0.getValue();
      assertNotNull(string0);
      assertEquals("w7 F ", option0.getDescription());
      assertFalse(option0.hasValueSeparator());
      assertEquals("Z8DkJ", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Option option0 = new Option("$0f", "$0f");
      String string0 = option0.getKey();
      assertNotNull(string0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Option option0 = new Option("V", true, "");
      option0.getValueSeparator();
      assertEquals("", option0.getDescription());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      assertNotNull(option_Builder0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      boolean boolean0 = option0.hasOptionalArg();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      Class<Integer> class0 = Integer.class;
      option0.setType(class0);
      assertFalse(option0.hasArgName());
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      String string0 = option0.toString();
      assertEquals("[ Option null [ARG] :: null :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Option option0 = new Option((String) null, true, "}LSE_O ryddUOSH#(");
      String string0 = option0.toDeprecatedString();
      assertFalse(option0.hasLongOpt());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder0.deprecated(deprecatedAttributes0);
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      String string0 = option0.toDeprecatedString();
      assertEquals((-1), option0.getArgs());
      assertEquals("Option 'null''q1(}w6AZ}nW6Y)nF(=1': Deprecated", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("bX0omUz2YMll1)9xo1y");
      Option.Builder option_Builder1 = option_Builder0.hasArgs();
      Option option0 = option_Builder1.get();
      option0.processValue("bX0omUz2YMll1)9xo1y");
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasArg());
      assertFalse(option0.hasValueSeparator());
      assertFalse(boolean0);
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("bX0omUz2YMll1)9xo1y");
      Option.Builder option_Builder1 = option_Builder0.hasArgs();
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.requiresArg();
      assertEquals((-2), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.optionalArg(true);
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.requiresArg();
      assertEquals(1, option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("value");
      Option option0 = option_Builder0.get();
      // Undeclared exception!
      try { 
        option0.processValue("org.apache.commons.cli.ParseException");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder1.get();
      String string0 = option0.toString();
      assertEquals((-1), option0.getArgs());
      assertEquals("[ Option null q1(}w6AZ}nW6Y)nF(=1 Deprecated :: null :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      boolean boolean0 = option0.hasLongOpt();
      assertEquals("", option0.getLongOpt());
      assertEquals("", option0.getDescription());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_LLOWED", "NO_ARGS_LLOWED");
      boolean boolean0 = option0.hasLongOpt();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("bX0omUz2YMll1)9xo1y");
      Option.Builder option_Builder1 = option_Builder0.hasArgs();
      Option option0 = option_Builder1.get();
      assertFalse(option0.isDeprecated());
      
      String string0 = option0.toString();
      assertEquals("[ Option null bX0omUz2YMll1)9xo1y[ARG...] :: null :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("bX0omUz2YMll1)9xo1y");
      Option option0 = option_Builder1.get();
      option0.setArgName("");
      boolean boolean0 = option0.hasArgName();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt(" :: ");
      option_Builder1.argName(" :: ");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasArgName();
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasArgName();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      String[] stringArray0 = option0.getValues();
      assertEquals("", option0.getDescription());
      assertEquals("", option0.getLongOpt());
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.optionalArg(true);
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      option0.processValue(" since ");
      String[] stringArray0 = option0.getValues();
      assertEquals(1, option0.getArgs());
      assertFalse(option0.hasValueSeparator());
      assertTrue(option0.hasOptionalArg());
      assertNotNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      String string0 = option0.getValue("o-_");
      assertEquals("", option0.getLongOpt());
      assertNotNull(string0);
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Option option0 = new Option("mwD", "mwD");
      option0.getValue((-1));
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.setArgs((-2));
      option0.processValue("n!d|EO)TLdEZ`'04Ev?");
      try { 
        option0.getValue((-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      option0.getValue();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Option option0 = new Option((String) null, true, "}LSE_O ryddUOSH#(");
      option0.processValue("}LSE_O ryddUOSH#(");
      String string0 = option0.getValue((String) null);
      assertNotNull(string0);
      assertFalse(option0.hasLongOpt());
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      String string0 = option0.getKey();
      assertNotNull(string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      option_Builder0.longOpt("");
      Option option1 = option_Builder0.get();
      boolean boolean0 = option0.equals(option1);
      assertFalse(boolean0);
      assertEquals((-1), option1.getArgs());
      assertEquals("", option0.getLongOpt());
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      Option option1 = new Option("value", true, "value");
      boolean boolean0 = option0.equals(option1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      Option option1 = (Option)option0.clone();
      boolean boolean0 = option1.equals(option0);
      assertTrue(boolean0);
      assertEquals("", option1.getDescription());
      assertEquals("", option1.getLongOpt());
      assertNotSame(option1, option0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      boolean boolean0 = option0.equals(option0);
      assertEquals("", option0.getDescription());
      assertTrue(boolean0);
      assertEquals("", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.equals(option_Builder0);
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      assertEquals(1, option0.getArgs());
      
      option0.processValue("");
      boolean boolean0 = option0.requiresArg();
      assertFalse(option0.hasValueSeparator());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg(false);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      option0.setType((Object) null);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      option0.getOpt();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Option option0 = new Option("9", "9", false, "9");
      // Undeclared exception!
      try { 
        option0.addValue("org.apache.commons.cli.Option");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      String string0 = option0.getLongOpt();
      assertEquals(1, option0.getArgs());
      assertEquals("", option0.getDescription());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      option0.hashCode();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Option option0 = new Option("Z8DkJ", "Z8DkJ", true, "Z8DkJ");
      option0.isRequired();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      option0.getSince();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Option option0 = new Option("mwD", "mwD");
      String string0 = option0.getDescription();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      int int0 = option0.getArgs();
      assertEquals(1, int0);
      assertEquals("", option0.getDescription());
      assertEquals("", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      option0.clearValues();
      assertEquals("", option0.getDescription());
      assertEquals(1, option0.getArgs());
      assertEquals("", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      option0.getDeprecated();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.valueSeparator('s');
      option_Builder0.hasArg();
      option_Builder0.longOpt("q1(}w6AZ}nW6Y)nF(=1");
      Option option0 = option_Builder0.get();
      assertTrue(option0.hasArg());
      
      option0.processValue(" since ");
      assertTrue(option0.hasValueSeparator());
      assertEquals('s', option0.getValueSeparator());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      option0.setArgs((-1590));
      // Undeclared exception!
      try { 
        option0.processValue("uv~:uLGO@8|^igDV");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      boolean boolean0 = option0.hasArg();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      int int0 = option0.getId();
      assertEquals(118, int0);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("value");
      Option option0 = option_Builder0.get();
      option0.getValuesList();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      option0.setOptionalArg(false);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasOptionalArg());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Option option0 = new Option("value", "value", true, "value");
      option0.setValueSeparator('{');
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals('{', option0.getValueSeparator());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "");
      Object object0 = option0.getType();
      option0.setType(object0);
      assertTrue(option0.hasArg());
      assertEquals("", option0.getDescription());
      assertEquals("", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArgs();
      option_Builder1.longOpt("$H<}h");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.hasArg();
      assertTrue(boolean0);
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.desc("");
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      Option.Builder option_Builder2 = option_Builder1.optionalArg(true);
      assertSame(option_Builder2, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.deprecated();
      option_Builder1.option("value");
      Option option0 = option_Builder1.get();
      String string0 = option0.toDeprecatedString();
      assertEquals((-1), option0.getArgs());
      assertEquals("Option 'value': Deprecated", string0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required();
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      assertSame(option_Builder0, option_Builder1);
  }
}
